"""Run-directory management for the HTTP API.

A *run* is one execution of the RadVel pipeline (fit → mcmc/ns → derive →
... → report). Each run owns a directory under :attr:`Settings.runs_dir`,
named by a 12-character URL-safe slug. The directory holds:

* ``setup.json``      — the original :class:`RunCreateRequest` payload
* ``setup.py``        — a tiny generated shim that the existing
  :func:`radvel.utils.initialize_posterior` loader reads. The shim
  populates module-level globals from ``setup.json`` so the legacy
  driver path keeps working with no changes.
* ``meta.json``       — created/updated metadata (radvel version, ``starname``)
* ``<slug>_radvel.stat`` and pickles — written by the existing driver
  functions exactly as they would in a CLI run.
"""

from __future__ import annotations

import datetime as _dt
import json
import os
import re
import secrets
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator, List, Optional

import radvel
from radvel.driver import load_status

from .config import Settings, get_settings


_SLUG_ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
_SLUG_RE = re.compile(r"^r-[A-Za-z0-9_-]{10}$")
SETUP_SHIM = '''\
"""Generated by radvel.api — DO NOT EDIT.

Loads the JSON configuration sitting next to this file (named
``<basename>.json``) and exposes its fields as module-level globals so
:func:`radvel.utils.initialize_posterior` keeps working unchanged.
"""
import json as _json
import os as _os

from radvel.utils import _namespace_from_dict as _ns_from_dict

_HERE = _os.path.dirname(_os.path.abspath(__file__))
_JSON = _os.path.splitext(_os.path.basename(__file__))[0] + ".json"
with open(_os.path.join(_HERE, _JSON)) as _f:
    _CONFIG = _json.load(_f)

_NS = _ns_from_dict(_CONFIG)
for _k, _v in vars(_NS).items():
    globals()[_k] = _v
del _NS, _CONFIG, _HERE, _JSON, _ns_from_dict, _json, _os, _f
'''


def make_run_id() -> str:
    """Return a 12-char URL-safe run identifier."""
    suffix = "".join(secrets.choice(_SLUG_ALPHABET) for _ in range(10))
    return "r-" + suffix


def is_valid_run_id(value: str) -> bool:
    """True if ``value`` matches the on-disk slug shape (path-traversal safe)."""
    return bool(_SLUG_RE.fullmatch(value))


@dataclass(frozen=True)
class RunRecord:
    """A handle for a run directory and its persisted metadata."""

    run_id: str
    outputdir: Path
    starname: str
    fitting_basis: str
    nplanets: int
    radvel_version: str
    created_at: _dt.datetime

    @property
    def setup_json(self) -> Path:
        return self.outputdir / "{}.json".format(self.run_id)

    @property
    def setup_py(self) -> Path:
        return self.outputdir / "{}.py".format(self.run_id)

    @property
    def meta_json(self) -> Path:
        return self.outputdir / "meta.json"

    @property
    def stat_file(self) -> Path:
        return self.outputdir / "{}_radvel.stat".format(self.run_id)


class RunNotFound(LookupError):
    """Raised when a caller references an unknown ``run_id``."""


class RunRegistry:
    """Filesystem-backed registry of runs.

    Holds no in-memory state of its own — every call reads the run
    directory. This keeps the API restart-resilient: state survives
    container restarts because it lives on the mounted ``/data`` volume.
    """

    def __init__(self, settings: Optional[Settings] = None) -> None:
        self.settings = settings or get_settings()
        self.runs_dir = self.settings.runs_dir
        self.runs_dir.mkdir(parents=True, exist_ok=True)

    # ---- lifecycle -----------------------------------------------------

    def create(self, payload: dict, starname: str, fitting_basis: str,
               nplanets: int) -> RunRecord:
        """Materialise a new run directory from a setup payload.

        The payload should already be validated against
        :class:`radvel.api.schemas.RunCreateRequest`; this method just
        serialises it.
        """
        run_id = make_run_id()
        outdir = self.runs_dir / run_id
        outdir.mkdir(parents=True, exist_ok=False)

        setup_json = outdir / "{}.json".format(run_id)
        setup_py = outdir / "{}.py".format(run_id)
        with open(setup_json, "w") as f:
            json.dump(payload, f, indent=2, sort_keys=True, default=_json_default)
        with open(setup_py, "w") as f:
            f.write(SETUP_SHIM)

        created_at = _dt.datetime.now(_dt.timezone.utc)
        meta = {
            "run_id": run_id,
            "starname": starname,
            "fitting_basis": fitting_basis,
            "nplanets": nplanets,
            "radvel_version": radvel.__version__,
            "created_at": created_at.isoformat(),
        }
        with open(outdir / "meta.json", "w") as f:
            json.dump(meta, f, indent=2, sort_keys=True)

        return RunRecord(
            run_id=run_id,
            outputdir=outdir,
            starname=starname,
            fitting_basis=fitting_basis,
            nplanets=nplanets,
            radvel_version=radvel.__version__,
            created_at=created_at,
        )

    def create_from_py(self, source_bytes: bytes) -> RunRecord:
        """Materialise a run from an uploaded ``.py`` setup file.

        Caller must have already verified the
        ``RADVEL_API_ALLOW_PY_UPLOAD`` flag is on — this method does not
        re-check, because allowing it executes arbitrary Python.

        The legacy CLI loads setup files by importing them, so we save
        the file as ``<run_id>.py`` and then call
        :func:`radvel.utils.initialize_posterior` once just to extract
        ``starname``, ``fitting_basis``, ``nplanets`` for the metadata.
        Any import-time failure surfaces as ``ValueError`` and the
        caller turns it into a 4xx.
        """
        run_id = make_run_id()
        outdir = self.runs_dir / run_id
        outdir.mkdir(parents=True, exist_ok=False)
        setup_py = outdir / "{}.py".format(run_id)
        setup_py.write_bytes(source_bytes)

        try:
            P, _ = radvel.utils.initialize_posterior(str(setup_py))
        except Exception as exc:
            shutil.rmtree(outdir, ignore_errors=True)
            raise ValueError(
                "uploaded setup failed to import: {}".format(exc)
            ) from exc

        starname = getattr(P, "starname", "unnamed")
        fitting_basis = getattr(P, "fitting_basis", "")
        nplanets = int(getattr(P, "nplanets", 0))

        created_at = _dt.datetime.now(_dt.timezone.utc)
        meta = {
            "run_id": run_id,
            "starname": starname,
            "fitting_basis": fitting_basis,
            "nplanets": nplanets,
            "radvel_version": radvel.__version__,
            "created_at": created_at.isoformat(),
            "source": "py_upload",
        }
        with open(outdir / "meta.json", "w") as f:
            json.dump(meta, f, indent=2, sort_keys=True)

        return RunRecord(
            run_id=run_id,
            outputdir=outdir,
            starname=starname,
            fitting_basis=fitting_basis,
            nplanets=nplanets,
            radvel_version=radvel.__version__,
            created_at=created_at,
        )

    def get(self, run_id: str) -> RunRecord:
        if not is_valid_run_id(run_id):
            raise RunNotFound(run_id)
        outdir = self.runs_dir / run_id
        meta_path = outdir / "meta.json"
        if not meta_path.is_file():
            raise RunNotFound(run_id)
        with open(meta_path) as f:
            meta = json.load(f)
        return RunRecord(
            run_id=meta["run_id"],
            outputdir=outdir,
            starname=meta.get("starname", ""),
            fitting_basis=meta.get("fitting_basis", ""),
            nplanets=int(meta.get("nplanets", 0)),
            radvel_version=meta.get("radvel_version", ""),
            created_at=_dt.datetime.fromisoformat(meta["created_at"]),
        )

    def delete(self, run_id: str, keep_files: bool = False) -> None:
        try:
            record = self.get(run_id)
        except RunNotFound:
            return  # idempotent
        if keep_files:
            (record.outputdir / "_deleted").write_text(
                _dt.datetime.now(_dt.timezone.utc).isoformat()
            )
        else:
            shutil.rmtree(record.outputdir, ignore_errors=True)

    def iter_runs(self) -> Iterator[RunRecord]:
        for entry in sorted(self.runs_dir.iterdir()):
            if not (entry.is_dir() and is_valid_run_id(entry.name)):
                continue
            try:
                yield self.get(entry.name)
            except RunNotFound:
                continue

    # ---- status --------------------------------------------------------

    def stat_dict(self, record: RunRecord) -> dict:
        """Return the parsed ``.stat`` file contents as a nested dict.

        Returns an empty dict if the file does not yet exist (i.e. no
        pipeline step has run for this run).
        """
        if not record.stat_file.is_file():
            return {}
        config = load_status(str(record.stat_file))
        out: dict = {}
        for section in config.sections():
            out[section] = dict(config.items(section))
        return out


def _json_default(value):
    """Fallback JSON serialiser for non-stdlib types (numpy, pandas)."""
    try:
        import numpy as np  # local import keeps numpy out of import graph
        if isinstance(value, (np.integer,)):
            return int(value)
        if isinstance(value, (np.floating,)):
            return float(value)
        if isinstance(value, np.ndarray):
            return value.tolist()
    except ImportError:
        pass
    if hasattr(value, "isoformat"):
        return value.isoformat()
    if isinstance(value, Path):
        return os.fspath(value)
    raise TypeError("Object of type {} is not JSON serialisable".format(type(value).__name__))
