language: python

python:
  - "2.7"
  - "3.4"
 
# install dependencies
install:
  - pip install -r requirements.txt # installs all dependencies listed in requirements.txt
  - pip install radvel
#  - python setup.py install         # installs radvel
#  - python setup.py build_ext -i    # tells radvel how to call kepler c code

# configure a headless display using xvbf to test plot generation
before_script: 
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

# run all tests in "getting started" docs
script:
   - radvel fit -s example_planets/epic203771098.py
   - radvel --help
   - radvel plot -t rv -s example_planets/epic203771098.py
   - radvel mcmc -s example_planets/epic203771098.py
   - radvel plot -t rv corner trend -s example_planets/epic203771098.py
   - radvel report -s example_planets/epic203771098.py
   - radvel derive -s example_planets/epic203771098.py
   - radvel plot -t derived -s example_planets/epic203771098.py
   - radvel bic -t nplanets -s example_planets/epic203771098.py
   - radvel table -t params priors nplanets -s example_planets/epic203771098.py
