language: python

python:
  - "2.7"
  - "3.4"
  
# install dependencies
install:
  - pip install -r requirements.txt
  - pip install radvel
  
# command to run tests
script:
   - python travis_test.py
