language: python

python:
  - "2.7"
  - "3.4"
  
# install dependencies
install:
  - pip install -r requirements.txt # installs all dependencies listed in requirements.txt
  - python setup.py install         # installs radvel
  - python setup.py build_ext -i    # tells radvel how to call kepler c code
  
# command to run tests
script:
   - cd example_planets
   - pwd
   - radvel fit -s epic203771098.py
   - cd ..
   - python travis_test.py
