language: python

services:
  - docker

before_install:
  - pwd
  - ls
  - docker build --tag radvel .

before_script:
  - "export DISPLAY=:99.0"
  - sleep 2 # give xvfb some time to start

script:
  - docker run radvel

after_success:
  - coveralls
